version: '3.8'
services:
  app:
    build: /home/zachary/code/dino-app
    restart: unless-stopped
    env_file: ./.env
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DATABASE
      - DB_PORT=$DATABASE_PORT
    # stdin_open: true
    # tty: true 
